query getArticles {
  articles {
    slug,
    headline,
    description,
    videoUrl,
    content,
    readingTime,
    createdAt,
    publishedAt,
    updatedAt,
    coverImage {
      url
    },
    tags {
      title,
      theme
    },
    author {
      fullName,
      avatar {
        url(transformation: {image: {resize: {height: 40, width: 40}}})
      }
    }
  }
}