query getProject($slug: String!){
  project(where: { slug: $slug }) {
    id,
    title,
    slug,
    description,
    challenge,
    solution,
    url,
    client,
    clientDescription,
    color {
      hex
    },
    roles {
      title
    },
    tools {
      title
    }
    imageHero {
      url
    },
    imageScreen {
      url
    },
    content
  }
}