query getProjects {
  projects {
    id,
    title,
    slug,
    clientDescription,
    color {
      hex
    },
    roles {
      title
    }
    imageCard {
      url
    },
    imageHero {
      url
    },
    imageScreen {
      url
    }
  }
}